### PR TITLE
Missing package to build tinycore container image.

### LINKED ISSUE #22: Patch is missing to build tinycore container image
Making the container image for tinycore fails because `patch` is no longer in alpine base container anymore 
-- or that is at least the only explanation I've found

The fix is easy as there is a package for that : https://pkgs.alpinelinux.org/packages?name=patch&branch=v3.12

PR coming very soon

### PR DESCRIPTION
**Pull request by malikbenkirane**
Missing package to build tinycore container image.

### CODE REVIEW

**Comment by afbjorklund** [comment]
> Missing package to build tinycore container image.

The comment here looks much better than the actual commit message, "Fix #22" :-)

We should also make a PR for upstream, https://github.com/tatsushid/docker-tinycore

https://github.com/tatsushid/docker-tinycore/blob/master/11.0/x86_64/src/Dockerfile

**Comment by malikbenkirane** [comment]
>The comment here looks much better than the actual commit message, "Fix #22" :-)

Sorry, I've done that in a hurry, hopefully GitHub is smart enough to link the commit message to the corresponding issue.

**Comment by malikbenkirane** [comment]
>We should also make a PR for upstream, https://github.com/tatsushid/docker-tinycore
>
>https://github.com/tatsushid/docker-tinycore/blob/master/11.0/x86_64/src/Dockerfile

this was  a quick one https://github.com/tatsushid/docker-tinycore/pull/12

**Comment by afbjorklund** [comment]
Cherry-picked in 217590c4fcb7387575c8f12d206568a819807458, thanks!

**Pull request closed without merging**
